spring:
  application:
    name: user-management
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com"
    issuer-uri: "https://securetoken.google.com/springboot-firebaseauth"
  datasource:
    url: jdbc:postgresql://localhost:5455/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.TYPE: TRACE
    org.springframework.web: DEBUG